# Generated by Django 6.0 on 2025-12-15 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("clave", models.CharField(max_length=100, unique=True)),
                ("valor", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("seguridad", "Seguridad"),
                            ("notificaciones", "Notificaciones"),
                            ("algoritmos", "Algoritmos"),
                            ("integraciones", "Integraciones"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("editable", models.BooleanField(default=True)),
                ("requiere_restart", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["tipo", "clave"],
            },
        ),
        migrations.CreateModel(
            name="ReporteSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("estadistico", "Estadístico"),
                            ("auditoria", "Auditoría"),
                            ("rendimiento", "Rendimiento"),
                            ("seguridad", "Seguridad"),
                            ("uso", "Uso del Sistema"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "frecuencia",
                    models.CharField(
                        choices=[
                            ("diario", "Diario"),
                            ("semanal", "Semanal"),
                            ("mensual", "Mensual"),
                            ("trimestral", "Trimestral"),
                            ("anual", "Anual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("parametros", models.JSONField(default=dict)),
                ("activo", models.BooleanField(default=True)),
                ("ultima_ejecucion", models.DateTimeField(blank=True, null=True)),
                ("proxima_ejecucion", models.DateTimeField(blank=True, null=True)),
                ("ejecuciones_exitosas", models.PositiveIntegerField(default=0)),
                ("ejecuciones_fallidas", models.PositiveIntegerField(default=0)),
                ("ultimo_resultado", models.TextField(blank=True)),
                (
                    "archivo_reporte",
                    models.FileField(
                        blank=True, null=True, upload_to="reportes/sistema/%Y/%m/"
                    ),
                ),
            ],
            options={
                "ordering": ["tipo", "frecuencia", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Administrador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("email_institucional", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=15)),
                ("cargo", models.CharField(default="Administrador", max_length=100)),
                ("departamento", models.CharField(default="TI", max_length=100)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("suspendido", "Suspendido"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("fecha_ingreso", models.DateTimeField(auto_now_add=True)),
                ("ultimo_acceso", models.DateTimeField(blank=True, null=True)),
                ("puede_gestionar_usuarios", models.BooleanField(default=True)),
                ("puede_configurar_sistema", models.BooleanField(default=False)),
                ("puede_ver_auditoria", models.BooleanField(default=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="administrador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["apellidos", "nombres"],
            },
        ),
        migrations.CreateModel(
            name="BackupSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("completo", "Backup Completo"),
                            ("base_datos", "Base de Datos"),
                            ("archivos", "Archivos"),
                            ("configuracion", "Configuración"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("ejecutando", "Ejecutando"),
                            ("completado", "Completado"),
                            ("fallido", "Fallido"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(blank=True, null=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "archivo_backup",
                    models.FileField(blank=True, null=True, upload_to="backups/%Y/%m/"),
                ),
                ("tamano_bytes", models.BigIntegerField(blank=True, null=True)),
                ("checksum", models.CharField(blank=True, max_length=128)),
                (
                    "ubicacion_almacenamiento",
                    models.CharField(blank=True, max_length=500),
                ),
                (
                    "ejecutado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="NotificacionSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=200)),
                ("mensaje", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("sistema", "Sistema"),
                            ("mantenimiento", "Mantenimiento"),
                            ("seguridad", "Seguridad"),
                            ("actualizacion", "Actualización"),
                            ("alerta", "Alerta"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        default="media",
                        max_length=20,
                    ),
                ),
                ("leida", models.BooleanField(default=False)),
                ("fecha_lectura", models.DateTimeField(blank=True, null=True)),
                ("fecha_expiracion", models.DateTimeField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "creada_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notificaciones_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destinatarios",
                    models.ManyToManyField(
                        blank=True,
                        related_name="notificaciones_recibidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "roles_destinatarios",
                    models.ManyToManyField(
                        blank=True, related_name="notificaciones", to="auth.group"
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="LogSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("mensaje", models.TextField()),
                ("modulo", models.CharField(max_length=100)),
                ("funcion", models.CharField(blank=True, max_length=100)),
                ("linea", models.PositiveIntegerField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("excepcion_tipo", models.CharField(blank=True, max_length=100)),
                ("excepcion_mensaje", models.TextField(blank=True)),
                ("traceback", models.TextField(blank=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(fields=["fecha"], name="administrac_fecha_e4980f_idx"),
                    models.Index(fields=["nivel"], name="administrac_nivel_7bfc26_idx"),
                    models.Index(
                        fields=["modulo"], name="administrac_modulo_8f4a39_idx"
                    ),
                ],
            },
        ),
    ]
