# Generated by Django 5.0 on 2025-12-17 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_id",
                    models.CharField(
                        help_text="Identificador único del caso",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "primary_diagnosis",
                    models.CharField(help_text="Diagnóstico primario", max_length=255),
                ),
                (
                    "specialty_required",
                    models.CharField(
                        help_text="Especialidad requerida", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Descripción detallada del caso"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Enviado"),
                            ("paid", "Pagado"),
                            ("in_review", "En Revisión"),
                            ("clarification_needed", "Necesita Aclaración"),
                            ("opinion_complete", "Opinión Completa"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="submitted",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_at",
                    models.DateTimeField(
                        blank=True, help_text="Fecha de asignación al médico", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="Fecha de completación", null=True
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "doctor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctor_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"role": "patient"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Caso",
                "verbose_name_plural": "Casos",
                "db_table": "cases_case",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("diagnostic_report", "Informe Diagnóstico"),
                            ("biopsy_report", "Informe de Biopsia"),
                            ("imaging", "Imágenes Diagnósticas"),
                            ("lab_results", "Resultados de Laboratorio"),
                            ("medical_history", "Historial Médico"),
                            ("other", "Otro"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Archivo del documento (debe estar cifrado)",
                        upload_to="cases/documents/%Y/%m/%d/",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Nombre original del archivo", max_length=255
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="cases.case",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento del Caso",
                "verbose_name_plural": "Documentos del Caso",
                "db_table": "cases_casedocument",
            },
        ),
        migrations.CreateModel(
            name="SecondOpinion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opinion_text",
                    models.TextField(
                        help_text="Opinión profesional (será cifrada en la BD)"
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(blank=True, help_text="Recomendaciones médicas"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_opinion",
                        to="cases.case",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opinions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Segunda Opinión",
                "verbose_name_plural": "Segundas Opiniones",
                "db_table": "cases_secondopinion",
            },
        ),
        migrations.CreateModel(
            name="CaseAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Creación"),
                            ("read", "Lectura"),
                            ("update", "Actualización"),
                            ("delete", "Eliminación"),
                            ("document_upload", "Carga de Documento"),
                            ("opinion_added", "Opinión Agregada"),
                            ("clarification_requested", "Aclaración Solicitada"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Descripción adicional del evento"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP del usuario que realizó la acción",
                        null=True,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="cases.case",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Auditoría del Caso",
                "verbose_name_plural": "Registros de Auditoría de Casos",
                "db_table": "cases_caseauditlog",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["case", "-timestamp"],
                        name="cases_casea_case_id_b21192_idx",
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="cases_casea_user_id_6843f7_idx",
                    ),
                ],
            },
        ),
    ]
