# Generated by Django 6.0 on 2025-12-17 16:52

import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="casedocument",
            name="is_anonymized",
            field=models.BooleanField(
                default=False, help_text="Indica si el archivo fue anonimizado"
            ),
        ),
        migrations.AddField(
            model_name="casedocument",
            name="s3_file_path",
            field=models.CharField(
                blank=True,
                help_text="Ruta/Key en S3 para el archivo (presigned upload)",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("PROCESSING", "Processing"),
                    ("PAID", "Paid"),
                    ("IN_REVIEW", "In Review"),
                    ("OPINION_COMPLETE", "Opinion Complete"),
                    ("CLOSED", "Closed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="DRAFT",
                max_length=30,
            ),
        ),
    ]
