# Generated by Django 6.0 on 2025-12-19 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0002_casedocument_is_anonymized_casedocument_s3_file_path_and_more"),
        ("medicos", "0003_localidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="diagnosis_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="localidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="medicos.localidad",
            ),
        ),
    ]
