# Generated by Django 6.0 on 2026-02-16 14:00

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_case_diagnosis_date_case_localidad'),
        ('medicos', '0004_tipocancer_medicalgroup_doctorgroupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='estadio',
            field=models.CharField(blank=True, choices=[('I', 'Estadio I'), ('II', 'Estadio II'), ('III', 'Estadio III'), ('IV', 'Estadio IV'), ('N/A', 'No aplica')], help_text='Estadio del cáncer', max_length=10),
        ),
        migrations.AddField(
            model_name='case',
            name='fecha_limite',
            field=models.DateField(blank=True, help_text='Fecha límite para resolver el caso', null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='medical_group',
            field=models.ForeignKey(blank=True, help_text='Grupo médico asignado al caso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='medicos.medicalgroup'),
        ),
        migrations.AddField(
            model_name='case',
            name='objetivo_consulta',
            field=models.TextField(blank=True, help_text='Objetivo de la consulta'),
        ),
        migrations.AddField(
            model_name='case',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Médico responsable del caso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_responsable', to='medicos.medico'),
        ),
        migrations.AddField(
            model_name='case',
            name='tipo_cancer',
            field=models.ForeignKey(blank=True, help_text='Tipo de cáncer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='medicos.tipocancer'),
        ),
        migrations.AddField(
            model_name='case',
            name='tratamiento_propuesto_original',
            field=models.TextField(blank=True, help_text='Tratamiento propuesto originalmente'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='description',
            field=models.CharField(blank=True, help_text='Descripción del documento', max_length=255),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='mime_type',
            field=models.CharField(blank=True, help_text='Tipo MIME del archivo', max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=django_fsm.FSMField(choices=[('DRAFT', 'Borrador'), ('SUBMITTED', 'Enviado'), ('ASSIGNED', 'Asignado'), ('PROCESSING', 'Procesando'), ('MDT_IN_PROGRESS', 'En Análisis por MDT'), ('MDT_COMPLETED', 'Discusión MDT Cerrada'), ('REPORT_DRAFT', 'Informe en Redacción'), ('REPORT_COMPLETED', 'Informe Completado'), ('OPINION_COMPLETE', 'Opinión Completa'), ('CLOSED', 'Cerrado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='file',
            field=models.FileField(help_text='Archivo del documento', upload_to='cases/documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='s3_file_path',
            field=models.CharField(blank=True, help_text='Ruta/Key en S3 para el archivo', max_length=1024),
        ),
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion', models.CharField(choices=[('acuerdo', 'Acuerdo con tratamiento propuesto'), ('desacuerdo', 'Desacuerdo con tratamiento propuesto'), ('consenso_parcial', 'Consenso parcial')], help_text='Conclusión del comité', max_length=20)),
                ('justificacion', models.TextField(help_text='Justificación de la conclusión')),
                ('recomendaciones', models.TextField(help_text='Recomendaciones médicas')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('pdf_file', models.FileField(blank=True, help_text='PDF del informe generado', null=True, upload_to='cases/reports/%Y/%m/')),
                ('firma_electronica', models.CharField(blank=True, help_text='Hash SHA-256 del contenido del informe', max_length=64)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informe_final', to='cases.case')),
                ('redactado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_redactados', to='medicos.medico')),
            ],
            options={
                'verbose_name': 'Informe Final',
                'verbose_name_plural': 'Informes Finales',
                'db_table': 'cases_finalreport',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='MedicalOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.CharField(choices=[('acuerdo', 'De acuerdo con el tratamiento propuesto'), ('desacuerdo', 'En desacuerdo con el tratamiento propuesto'), ('abstencion', 'Se abstiene de emitir opinión')], help_text='Voto del médico', max_length=20)),
                ('comentario_privado', models.TextField(blank=True, help_text='Comentario privado (solo visible para el grupo médico)')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opiniones', to='cases.case')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opiniones_casos', to='medicos.medico')),
            ],
            options={
                'verbose_name': 'Opinión Médica',
                'verbose_name_plural': 'Opiniones Médicas',
                'db_table': 'cases_medicalopinion',
                'ordering': ['-fecha_emision'],
                'constraints': [models.UniqueConstraint(fields=('case', 'doctor'), name='unique_opinion_per_case_doctor')],
            },
        ),
    ]
