# Generated by Django 5.0 on 2026-02-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_case_estadio_case_fecha_limite_case_medical_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casedocument",
            name="file",
            field=models.FileField(
                help_text="Archivo del documento", upload_to="cases/%Y/%m/%d/"
            ),
        ),
    ]
