# Generated by Django 5.0 on 2026-02-16 14:41

import cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0005_alter_casedocument_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casedocument",
            name="file",
            field=models.FileField(
                help_text="Archivo del documento",
                upload_to=cases.models.case_document_upload_path,
            ),
        ),
    ]
