# Generated by Django 6.0 on 2026-02-16 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_alter_casedocument_file"),
        ("medicos", "0005_doctorgroupmembership_disponible_asignacion_auto_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlgoritmoConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "nombre",
                    models.CharField(
                        default="configuracion_default", max_length=100, unique=True
                    ),
                ),
                (
                    "ponderacion_carga",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Peso de la carga actual vs antigüedad (0 = solo antigüedad, 100 = solo carga)",
                    ),
                ),
                (
                    "modo_estricto",
                    models.BooleanField(
                        default=False,
                        help_text="Si True, ignora ponderaciones y usa round-robin puro",
                    ),
                ),
                (
                    "limite_mensual_por_medico",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Límite máximo de casos por médico por mes",
                    ),
                ),
                (
                    "permitir_overrides",
                    models.BooleanField(
                        default=True,
                        help_text="Permite que el administrador asigne manualmente casos",
                    ),
                ),
                (
                    "respetar_disponibilidad",
                    models.BooleanField(
                        default=True,
                        help_text="Si True, no asigna a médicos marcados como no disponibles",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "modificado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configs_algoritmo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración del Algoritmo",
                "verbose_name_plural": "Configuraciones del Algoritmo",
            },
        ),
        migrations.CreateModel(
            name="AnatomicalRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("svg_path", models.TextField(blank=True)),
                ("svg_id", models.CharField(blank=True, max_length=50)),
                (
                    "sintomas_asociados",
                    models.JSONField(
                        default=list,
                        help_text="Lista de síntomas típicos de esta región",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "especialidades_sugeridas",
                    models.ManyToManyField(
                        related_name="regiones_anatomicas", to="medicos.especialidad"
                    ),
                ),
            ],
            options={
                "verbose_name": "Región Anatómica",
                "verbose_name_plural": "Regiones Anatómicas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="AsignacionAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.CharField(
                        help_text="Resultado: asignado, saltado, no_disponible",
                        max_length=50,
                    ),
                ),
                (
                    "motivo",
                    models.TextField(
                        help_text="Razón de la decisión (ej: 'Carga mínima', 'No disponible')"
                    ),
                ),
                ("score_carga", models.FloatField(blank=True, null=True)),
                ("score_antiguedad", models.FloatField(blank=True, null=True)),
                ("score_final", models.FloatField(blank=True, null=True)),
                ("es_override", models.BooleanField(default=False)),
                ("override_justificacion", models.TextField(blank=True)),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_asignaciones",
                        to="cases.case",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_asignacion",
                        to="cases.algoritmoconfig",
                    ),
                ),
                (
                    "medico_seleccionado",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asignaciones_recibidas",
                        to="medicos.medico",
                    ),
                ),
                (
                    "override_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overrides_asignacion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Asignación",
                "verbose_name_plural": "Logs de Asignación",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=200)),
                (
                    "contenido",
                    models.TextField(
                        help_text="Plantilla con variables como {{paciente}}, {{edad}}, etc."
                    ),
                ),
                (
                    "es_global",
                    models.BooleanField(
                        default=True,
                        help_text="Si True, es institucional; si False, es personal del médico",
                    ),
                ),
                ("esta_activa", models.BooleanField(default=True)),
                ("veces_usada", models.PositiveIntegerField(default=0)),
                (
                    "creador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plantillas_creadas",
                        to="medicos.medico",
                    ),
                ),
                (
                    "especialidad",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plantillas",
                        to="medicos.especialidad",
                    ),
                ),
                (
                    "tipo_cancer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plantillas",
                        to="medicos.tipocancer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla Clínica",
                "verbose_name_plural": "Plantillas Clínicas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ConsensusWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "fase",
                    models.CharField(
                        choices=[
                            ("DISCUSION", "Discusión Abierta"),
                            ("PROPUESTA", "Propuesta Redactada"),
                            ("VOTACION", "Votación Abierta"),
                            ("CONSENSO", "Consenso Alcanzado"),
                            ("DISENSO", "Disenso Registrado"),
                            ("BLOQUEADO", "Bloqueado - Más Info"),
                        ],
                        default="DISCUSION",
                        max_length=20,
                    ),
                ),
                (
                    "propuesta_consenso",
                    models.TextField(
                        blank=True,
                        help_text="Borrador de consenso redactado por el coordinador",
                    ),
                ),
                ("votos_a_favor", models.PositiveIntegerField(default=0)),
                ("votos_en_contra", models.PositiveIntegerField(default=0)),
                ("abstenciones", models.PositiveIntegerField(default=0)),
                (
                    "nivel_evidencia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("alta", "Alta - Unánime"),
                            ("moderada", "Moderada - Mayoría Simple"),
                            ("baja", "Baja - Disenso Significativo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("requiere_mas_informacion", models.BooleanField(default=False)),
                ("descripcion_info_requerida", models.TextField(blank=True)),
                ("fecha_limite_info", models.DateField(blank=True, null=True)),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_consenso", models.DateTimeField(blank=True, null=True)),
                ("esta_bloqueado", models.BooleanField(default=False)),
                (
                    "caso",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_consenso",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow de Consenso",
                "verbose_name_plural": "Workflows de Consenso",
            },
        ),
        migrations.CreateModel(
            name="ConsensusVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("numero_version", models.PositiveIntegerField()),
                ("contenido", models.TextField()),
                (
                    "notas_cambio",
                    models.TextField(
                        blank=True, help_text="Descripción de los cambios realizados"
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versiones_consenso",
                        to="medicos.medico",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versiones",
                        to="cases.consensusworkflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versión de Consenso",
                "verbose_name_plural": "Versiones de Consenso",
                "ordering": ["-numero_version"],
            },
        ),
        migrations.CreateModel(
            name="MDTMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("mensaje", "Mensaje"),
                            ("sistema", "Mensaje del Sistema"),
                            ("adjunto", "Adjunto"),
                        ],
                        default="mensaje",
                        max_length=20,
                    ),
                ),
                ("contenido", models.TextField()),
                (
                    "es_privado",
                    models.BooleanField(
                        default=False,
                        help_text="Si es True, solo el autor puede ver el mensaje",
                    ),
                ),
                ("esta_editado", models.BooleanField(default=False)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mdt_messages",
                        to="medicos.medico",
                    ),
                ),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mdt_messages",
                        to="cases.case",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="medicos.medicalgroup",
                    ),
                ),
                (
                    "leido_por",
                    models.ManyToManyField(
                        blank=True, related_name="mensajes_leidos", to="medicos.medico"
                    ),
                ),
                (
                    "mensaje_padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas",
                        to="cases.mdtmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["creado_en"],
            },
        ),
        migrations.CreateModel(
            name="MDTMessageAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("archivo", models.FileField(upload_to="mdt/attachments/%Y/%m/")),
                ("nombre_original", models.CharField(max_length=255)),
                ("tipo_mime", models.CharField(max_length=100)),
                ("tamano", models.PositiveIntegerField()),
                (
                    "mensaje",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjuntos",
                        to="cases.mdtmessage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OpinionDisidente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("opinion", models.TextField()),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opiniones_disidentes",
                        to="medicos.medico",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opiniones_disidentes",
                        to="cases.consensusworkflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opinión Disidente",
                "verbose_name_plural": "Opiniones Disidentes",
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tema",
                    models.CharField(
                        choices=[
                            ("light", "Claro"),
                            ("dark", "Oscuro"),
                            ("system", "Seguir Sistema"),
                        ],
                        default="system",
                        max_length=10,
                    ),
                ),
                ("idioma", models.CharField(default="es", max_length=10)),
                ("notificaciones_email", models.BooleanField(default=True)),
                ("notificaciones_push", models.BooleanField(default=True)),
                ("elementos_por_pagina", models.PositiveIntegerField(default=10)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferencias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferencia de Usuario",
                "verbose_name_plural": "Preferencias de Usuarios",
            },
        ),
        migrations.CreateModel(
            name="UserPresence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("online", "Conectado"),
                            ("away", "Ausente"),
                            ("busy", "En Llamada/Videollamada"),
                            ("offline", "Desconectado"),
                        ],
                        default="offline",
                        max_length=20,
                    ),
                ),
                ("ultimo_heartbeat", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "caso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participantes_conectados",
                        to="cases.case",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presencias",
                        to="medicos.medico",
                    ),
                ),
            ],
            options={
                "ordering": ["-ultimo_heartbeat"],
            },
        ),
        migrations.CreateModel(
            name="ConsensusVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "voto",
                    models.CharField(
                        choices=[
                            ("aprueba", "Aprueba"),
                            ("aprueba_mod", "Aprueba con Modificaciones"),
                            ("alternativa", "Propone Alternativa"),
                            ("contraindicado", "Considera Contraindicado"),
                            ("abstiene", "Se Abstiene"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "justificacion",
                    models.TextField(blank=True, help_text="Razón del voto"),
                ),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votos_consenso",
                        to="medicos.medico",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votos",
                        to="cases.consensusworkflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voto de Consenso",
                "verbose_name_plural": "Votos de Consenso",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workflow", "medico"), name="unique_vote_per_workflow"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="mdtmessage",
            index=models.Index(
                fields=["caso", "-creado_en"], name="cases_mdtme_caso_id_1066e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mdtmessage",
            index=models.Index(
                fields=["grupo", "-creado_en"], name="cases_mdtme_grupo_i_b884ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userpresence",
            index=models.Index(
                fields=["usuario", "-ultimo_heartbeat"],
                name="cases_userp_usuario_b868a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userpresence",
            index=models.Index(
                fields=["caso", "estado"], name="cases_userp_caso_id_01c52a_idx"
            ),
        ),
    ]
