# Generated by Django 5.0 on 2026-03-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0007_algoritmoconfig_anatomicalregion_asignacionauditlog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="referring_institution",
            field=models.CharField(
                blank=True,
                help_text="Hospital o institución que emitió el diagnóstico",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="casedocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("resumen_historia_clinica", "Resumen de Historia Clínica"),
                    ("resultado_laboratorios", "Resultado de Laboratorios"),
                    ("resultado_imagenologia", "Resultado de Imagenología"),
                    ("imagenes", "Imágenes"),
                    ("resultado_biopsia", "Resultado de Biopsia"),
                    ("otros_documentos", "Otros Documentos Relevantes"),
                ],
                max_length=50,
            ),
        ),
    ]
