# Generated by Django 5.0 on 2026-03-11 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0008_add_referring_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mdtmessage",
            name="caso",
            field=models.ForeignKey(
                blank=True,
                help_text="Caso associated (optional for general group chat)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mdt_messages",
                to="cases.case",
            ),
        ),
    ]
