# Generated by Django 5.0 on 2026-03-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0009_make_caso_optional_in_mdtmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="primary_diagnosis",
            field=models.CharField(
                blank=True, help_text="Diagnóstico primario", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="specialty_required",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Especialidad requerida",
                max_length=100,
            ),
        ),
    ]
