# Generated by Django 5.0 on 2026-03-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0010_allow_null_primary_diagnosis"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="description",
            field=models.TextField(
                blank=True, null=True, help_text="Descripción detallada del caso"
            ),
        ),
    ]
