# Generated by Django 5.0 on 2026-03-24 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0011_alter_case_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="description",
        ),
    ]
