# Generated by Django 5.0 on 2026-03-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0012_remove_case_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="estadio",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I", "Estadio I"),
                    ("II", "Estadio II"),
                    ("III", "Estadio III"),
                    ("IV", "Estadio IV"),
                    ("N/A", "No aplica"),
                ],
                help_text="Estadio del cáncer",
                max_length=10,
                null=True,
            ),
        ),
    ]
