# Generated by Django 5.0 on 2026-03-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0013_alter_case_estadio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="estadio",
        ),
        migrations.RemoveField(
            model_name="case",
            name="objetivo_consulta",
        ),
        migrations.RemoveField(
            model_name="case",
            name="tratamiento_propuesto_original",
        ),
    ]
