# Generated by Django 6.0 on 2025-12-15 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlgoritmoConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("asignacion", "Asignación de Casos"),
                            ("notificacion", "Notificaciones"),
                            ("prioridad", "Priorización"),
                        ],
                        max_length=20,
                    ),
                ),
                ("configuracion", models.JSONField(default=dict)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("nombre", "tipo")},
            },
        ),
        migrations.CreateModel(
            name="ModuloSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("mantenimiento", "En Mantenimiento"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("fecha_activacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_desactivacion", models.DateTimeField(blank=True, null=True)),
                (
                    "dependencias",
                    models.ManyToManyField(blank=True, to="core.modulosistema"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Auditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_accion",
                    models.CharField(
                        choices=[
                            ("creacion", "Creación"),
                            ("modificacion", "Modificación"),
                            ("eliminacion", "Eliminación"),
                            ("acceso", "Acceso"),
                            ("sistema", "Sistema"),
                        ],
                        max_length=20,
                    ),
                ),
                ("modelo_afectado", models.CharField(max_length=100)),
                ("objeto_id", models.IntegerField(blank=True, null=True)),
                ("descripcion", models.TextField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(fields=["fecha"], name="core_audito_fecha_00c6d4_idx"),
                    models.Index(
                        fields=["usuario", "fecha"],
                        name="core_audito_usuario_b4b8b4_idx",
                    ),
                ],
            },
        ),
    ]
