# Generated by Django 6.0 on 2025-12-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Especialidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("codigo", models.CharField(blank=True, max_length=20, unique=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("activa", "Activa"), ("inactiva", "Inactiva")],
                        default="activa",
                        max_length=10,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Especialidades",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Institucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, unique=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("hospital", "Hospital"),
                            ("clinica", "Clínica"),
                            ("centro_salud", "Centro de Salud"),
                            ("consultorio", "Consultorio"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("direccion", models.TextField()),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("responsable", models.CharField(blank=True, max_length=100)),
                (
                    "estado",
                    models.CharField(
                        choices=[("activa", "Activa"), ("inactiva", "Inactiva")],
                        default="activa",
                        max_length=10,
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Instituciones",
                "ordering": ["nombre"],
            },
        ),
    ]
