# Generated by Django 6.0 on 2025-12-15 17:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medicos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CasoClinico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("diagnostico_actual", models.TextField()),
                ("tratamiento_actual", models.TextField(blank=True)),
                (
                    "prioridad",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="media",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("enviado", "Enviado"),
                            ("asignado", "Asignado"),
                            ("en_revision", "En Revisión"),
                            ("comite", "En Comité"),
                            ("concluido", "Concluido"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                ("fecha_sintomas", models.DateField(blank=True, null=True)),
                ("fecha_diagnostico", models.DateField(blank=True, null=True)),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                ("fecha_asignacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_conclusion", models.DateTimeField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("notas_admin", models.TextField(blank=True)),
                (
                    "comite_asignado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="medicos.comitemultidisciplinario",
                    ),
                ),
                (
                    "medico_asignado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="medicos.medico",
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoClinico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("historia_clinica", "Historia Clínica"),
                            ("examenes", "Exámenes de Laboratorio"),
                            ("imagenes", "Imágenes Diagnósticas"),
                            ("informes", "Informes Médicos"),
                            ("consentimiento", "Consentimiento Informado"),
                            ("otro", "Otro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("archivo", models.FileField(upload_to="documentos/casos/%Y/%m/")),
                ("descripcion", models.TextField(blank=True)),
                ("confidencial", models.BooleanField(default=False)),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="pacientes.casoclinico",
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
        migrations.AddField(
            model_name="casoclinico",
            name="documentos_clinicos",
            field=models.ManyToManyField(blank=True, to="pacientes.documentoclinico"),
        ),
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("cc", "Cédula de Ciudadanía"),
                            ("ce", "Cédula de Extranjería"),
                            ("ti", "Tarjeta de Identidad"),
                            ("pasaporte", "Pasaporte"),
                        ],
                        default="cc",
                        max_length=20,
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Solo números permitidos", regex="^\\d+$"
                            )
                        ],
                    ),
                ),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
                (
                    "genero",
                    models.CharField(
                        choices=[
                            ("masculino", "Masculino"),
                            ("femenino", "Femenino"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "estado_civil",
                    models.CharField(
                        choices=[
                            ("soltero", "Soltero/a"),
                            ("casado", "Casado/a"),
                            ("divorciado", "Divorciado/a"),
                            ("viudo", "Viudo/a"),
                            ("union_libre", "Unión Libre"),
                        ],
                        default="soltero",
                        max_length=20,
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Formato de teléfono inválido",
                                regex="^\\+?[\\d\\s\\-\\(\\)]+$",
                            )
                        ],
                    ),
                ),
                (
                    "telefono_alternativo",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Formato de teléfono inválido",
                                regex="^\\+?[\\d\\s\\-\\(\\)]+$",
                            )
                        ],
                    ),
                ),
                ("email_alternativo", models.EmailField(blank=True, max_length=254)),
                ("eps", models.CharField(max_length=100, verbose_name="EPS")),
                (
                    "regimen",
                    models.CharField(
                        choices=[
                            ("contributivo", "Contributivo"),
                            ("subsidiado", "Subsidiado"),
                            ("especial", "Especial"),
                            ("excepcion", "Excepción"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "grupo_sanguineo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ocupacion", models.CharField(blank=True, max_length=100)),
                ("direccion", models.TextField(blank=True)),
                ("ciudad", models.CharField(blank=True, max_length=100)),
                ("departamento", models.CharField(blank=True, max_length=100)),
                ("consentimiento_datos", models.BooleanField(default=False)),
                ("autorizacion_tratamiento", models.BooleanField(default=False)),
                ("fecha_consentimiento", models.DateTimeField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_inactivacion", models.DateTimeField(blank=True, null=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paciente",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["apellidos", "nombres"],
            },
        ),
        migrations.AddField(
            model_name="casoclinico",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="casos",
                to="pacientes.paciente",
            ),
        ),
        migrations.CreateModel(
            name="AntecedenteMedico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("personal", "Antecedente Personal"),
                            ("familiar", "Antecedente Familiar"),
                            ("quirurgico", "Antecedente Quirúrgico"),
                            ("alergia", "Alergia"),
                            ("medicamento", "Medicamento"),
                            ("habito", "Hábito"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("fecha_diagnostico", models.DateField(blank=True, null=True)),
                ("medico_tratante", models.CharField(blank=True, max_length=100)),
                ("activo", models.BooleanField(default=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="antecedentes",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_diagnostico"],
            },
        ),
        migrations.CreateModel(
            name="SolicitudSegundaOpinion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("motivo_solicitud", models.TextField()),
                ("especialidad_solicitada", models.CharField(max_length=100)),
                ("urgencia", models.BooleanField(default=False)),
                ("autorizacion_eps", models.BooleanField(default=False)),
                ("numero_autorizacion", models.CharField(blank=True, max_length=50)),
                ("medico_remitente", models.CharField(max_length=100)),
                ("institucion_remitente", models.CharField(max_length=100)),
                ("contacto_remitente", models.CharField(max_length=100)),
                ("aprobado", models.BooleanField(default=False)),
                ("fecha_aprobacion", models.DateTimeField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "caso",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitud",
                        to="pacientes.casoclinico",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="paciente",
            index=models.Index(
                fields=["numero_documento"], name="pacientes_p_numero__485b0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paciente",
            index=models.Index(
                fields=["nombres", "apellidos"], name="pacientes_p_nombres_2b26b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paciente",
            index=models.Index(fields=["activo"], name="pacientes_p_activo_97e8e7_idx"),
        ),
        migrations.AddIndex(
            model_name="casoclinico",
            index=models.Index(fields=["estado"], name="pacientes_c_estado_9269a1_idx"),
        ),
        migrations.AddIndex(
            model_name="casoclinico",
            index=models.Index(
                fields=["prioridad"], name="pacientes_c_priorid_72def8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casoclinico",
            index=models.Index(
                fields=["paciente"], name="pacientes_c_pacient_085ed5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="casoclinico",
            index=models.Index(fields=["uuid"], name="pacientes_c_uuid_97123b_idx"),
        ),
    ]
