# Generated by Django 6.0 on 2025-12-15 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medicos", "0001_initial"),
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reunioncomite",
            name="caso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reuniones_comite",
                to="pacientes.casoclinico",
            ),
        ),
        migrations.AddField(
            model_name="reunioncomite",
            name="comite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reuniones",
                to="medicos.comitemultidisciplinario",
            ),
        ),
        migrations.AddField(
            model_name="reunioncomite",
            name="medicos_participantes",
            field=models.ManyToManyField(
                blank=True, related_name="reuniones_participadas", to="medicos.medico"
            ),
        ),
        migrations.AddField(
            model_name="reunioncomite",
            name="moderador",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reuniones_moderadas",
                to="medicos.medico",
            ),
        ),
        migrations.AddField(
            model_name="revisioncaso",
            name="caso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisiones",
                to="pacientes.casoclinico",
            ),
        ),
        migrations.AddField(
            model_name="revisioncaso",
            name="medico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisiones",
                to="medicos.medico",
            ),
        ),
        migrations.AddIndex(
            model_name="medico",
            index=models.Index(
                fields=["numero_documento"], name="medicos_med_numero__af8e06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medico",
            index=models.Index(
                fields=["registro_medico"], name="medicos_med_registr_579f83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medico",
            index=models.Index(fields=["estado"], name="medicos_med_estado_017fec_idx"),
        ),
        migrations.AddIndex(
            model_name="medico",
            index=models.Index(
                fields=["disponible_segundas_opiniones"],
                name="medicos_med_disponi_d86161_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="disponibilidadmedico",
            unique_together={("medico", "dia_semana", "hora_inicio", "hora_fin")},
        ),
        migrations.AlterUniqueTogether(
            name="revisioncaso",
            unique_together={("caso", "medico")},
        ),
    ]
