# Generated by Django 6.0 on 2026-02-16 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_localidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(help_text='Código interno (ej: PULMON, MAMA)', max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('especialidad_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_cancer', to='medicos.especialidad')),
            ],
            options={
                'verbose_name': 'Tipo de Cáncer',
                'verbose_name_plural': 'Tipos de Cáncer',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MedicalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(help_text='Nombre del comité (ej: Comité de Pulmón)', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('quorum_config', models.PositiveSmallIntegerField(default=3, help_text='Número mínimo de médicos requeridos para tomar decisiones')),
                ('activo', models.BooleanField(default=True)),
                ('responsable_por_defecto', models.ForeignKey(blank=True, help_text='Médico responsable por defecto para nuevos casos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_como_responsable', to='medicos.medico')),
                ('tipo_cancer', models.ForeignKey(help_text='Tipo de cáncer que atiende este grupo', on_delete=django.db.models.deletion.CASCADE, related_name='grupos_medicos', to='medicos.tipocancer')),
            ],
            options={
                'verbose_name': 'Grupo Médico',
                'verbose_name_plural': 'Grupos Médicos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DoctorGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('es_responsable', models.BooleanField(default=False, help_text='Indica si este médico es el responsable del grupo')),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_grupo', to='medicos.medico')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='medicos.medicalgroup')),
            ],
            options={
                'verbose_name': 'Membresía de Médico',
                'verbose_name_plural': 'Membresías de Médicos',
                'ordering': ['-fecha_union'],
                'unique_together': {('medico', 'grupo')},
            },
        ),
    ]
