# Generated by Django 6.0 on 2026-02-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicos", "0004_tipocancer_medicalgroup_doctorgroupmembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorgroupmembership",
            name="disponible_asignacion_auto",
            field=models.BooleanField(
                default=True,
                help_text="Si está disponible para asignación automática de casos",
            ),
        ),
        migrations.AddField(
            model_name="doctorgroupmembership",
            name="fecha_salida",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctorgroupmembership",
            name="puede_declara_consenso",
            field=models.BooleanField(
                default=False,
                help_text="Si puede declarar consenso en nombre del grupo",
            ),
        ),
        migrations.AddField(
            model_name="doctorgroupmembership",
            name="puede_votar",
            field=models.BooleanField(
                default=True, help_text="Si puede emitir voto en decisiones de consenso"
            ),
        ),
        migrations.AddField(
            model_name="doctorgroupmembership",
            name="rol",
            field=models.CharField(
                choices=[
                    ("coordinador", "Coordinador"),
                    ("miembro_senior", "Miembro Senior"),
                    ("miembro_regular", "Miembro Regular"),
                    ("residente", "Residente (Observador)"),
                    ("invitado", "Especialista Invitado"),
                ],
                default="miembro_regular",
                help_text="Rol del médico en el grupo",
                max_length=20,
            ),
        ),
    ]
