# Generated by Django 5.0 on 2026-02-16 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicos", "0006_alter_comitemultidisciplinario_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="localidad",
            name="comite",
            field=models.ForeignKey(
                blank=True,
                help_text="Comité MDT que atiende casos de esta localidad",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="localidades",
                to="medicos.comitemultidisciplinario",
            ),
        ),
    ]
