# Generated by Django 5.0 on 2026-03-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicos", "0008_add_coordinador_to_comite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalgroup",
            name="tipo_cancer",
        ),
        migrations.AddField(
            model_name="medicalgroup",
            name="tipos_cancer",
            field=models.ManyToManyField(
                help_text="Tipos de cáncer que atiende este grupo",
                related_name="grupos_medicos",
                to="medicos.tipocancer",
            ),
        ),
        migrations.AlterField(
            model_name="medicalgroup",
            name="nombre",
            field=models.CharField(
                help_text="Nombre del comité (ej: Comité de Tumores Torácicos)",
                max_length=100,
                unique=True,
            ),
        ),
    ]
