# Generated by Django 5.0 on 2026-03-13 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicos", "0009_change_tipo_cancer_to_manytomany"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalgroup",
            name="tipos_cancer",
        ),
        migrations.AddField(
            model_name="tipocancer",
            name="grupo_medico",
            field=models.ForeignKey(
                blank=True,
                help_text="Grupo médico que maneja este tipo de cáncer (uno solo)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tipos_cancer",
                to="medicos.medicalgroup",
            ),
        ),
    ]
