# Generated by Django 5.0 on 2025-12-17 15:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email único para autenticación",
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("patient", "Paciente"), ("doctor", "Médico")],
                        default="patient",
                        help_text="Rol del usuario en el sistema",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el usuario puede acceder al sistema",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "auth_customuser",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Nombre completo del médico", max_length=255
                    ),
                ),
                (
                    "medical_license",
                    models.CharField(
                        help_text="Número de licencia médica",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("oncology", "Oncología"),
                            ("cardiology", "Cardiología"),
                            ("neurology", "Neurología"),
                            ("orthopedics", "Ortopedia"),
                            ("general", "Medicina General"),
                            ("other", "Otra"),
                        ],
                        help_text="Especialidad médica",
                        max_length=50,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Número de teléfono profesional", max_length=20
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True, help_text="Institución o clínica", max_length=255
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el médico puede recibir nuevos casos",
                    ),
                ),
                (
                    "max_concurrent_cases",
                    models.PositiveIntegerField(
                        default=10, help_text="Número máximo de casos simultáneos"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "doctor"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Médico",
                "verbose_name_plural": "Perfiles de Médicos",
                "db_table": "auth_doctorprofile",
            },
        ),
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Nombre completo del paciente", max_length=255
                    ),
                ),
                (
                    "identity_document",
                    models.CharField(
                        help_text="Cédula de identidad o pasaporte",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Número de teléfono de contacto", max_length=20
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, help_text="Fecha de nacimiento", null=True
                    ),
                ),
                (
                    "primary_diagnosis",
                    models.TextField(blank=True, help_text="Diagnóstico primario"),
                ),
                (
                    "medical_history",
                    models.TextField(
                        blank=True, help_text="Historial médico relevante"
                    ),
                ),
                (
                    "current_treatment",
                    models.TextField(blank=True, help_text="Tratamiento actual"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "patient"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Paciente",
                "verbose_name_plural": "Perfiles de Pacientes",
                "db_table": "auth_patientprofile",
            },
        ),
    ]
