# Generated by Django 5.0 on 2025-12-17 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(
                default=False, help_text="Indica si el email ha sido verificado"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el usuario puede acceder al sistema. Se activa después de verificar email",
            ),
        ),
        migrations.CreateModel(
            name="EmailVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="Token único de verificación",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Fecha y hora de expiración del token"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si el token ya ha sido utilizado",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora cuando el token fue utilizado",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Usuario asociado al token",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_token",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de Verificación",
                "verbose_name_plural": "Tokens de Verificación",
                "db_table": "auth_emailverificationtoken",
                "indexes": [
                    models.Index(fields=["token"], name="auth_emailv_token_02a79f_idx"),
                    models.Index(
                        fields=["expires_at"], name="auth_emailv_expires_b79f51_idx"
                    ),
                ],
            },
        ),
    ]
