# Generated by Django 5.0 on 2026-03-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0002_customuser_email_verified_alter_customuser_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="genero",
            field=models.CharField(
                choices=[
                    ("masculino", "Masculino"),
                    ("femenino", "Femenino"),
                    ("otro", "Otro"),
                    ("no_especificado", "No especificado"),
                ],
                default="no_especificado",
                help_text="Género del paciente",
                max_length=20,
            ),
        ),
    ]
