# Generated by Django 6.0 on 2026-02-16 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('asignacion_caso', 'Nuevo caso asignado'), ('nueva_opinion', 'Nueva opinión en caso'), ('recordatorio_voto', 'Recordatorio de votación'), ('votacion_cerrada', 'Votación cerrada'), ('informe_disponible', 'Informe final disponible'), ('caso_actualizado', 'Caso actualizado'), ('documento_subido', 'Nuevo documento subido')], help_text='Tipo de notificación', max_length=30)),
                ('titulo', models.CharField(help_text='Título de la notificación', max_length=200)),
                ('mensaje', models.TextField(help_text='Cuerpo del mensaje')),
                ('enlace', models.CharField(blank=True, help_text='URL de acción (opcional)', max_length=500)),
                ('leido', models.BooleanField(default=False, help_text='Indica si la notificación ha sido leída')),
                ('caso_id', models.CharField(blank=True, help_text='ID del caso relacionado', max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, help_text='Fecha en que se leyó la notificación', null=True)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['receptor', 'leido'], name='notificatio_recepto_a6c777_idx'), models.Index(fields=['receptor', '-fecha_creacion'], name='notificatio_recepto_fce3ef_idx')],
            },
        ),
    ]
