# Generated by Django 5.0 on 2026-03-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicos", "0010_change_tipo_cancer_to_fk"),
        ("notifications", "0002_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorinvitation",
            name="tipos_cancer_seleccionados",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tipos de cáncer que el médico podrá tratar",
                related_name="invitaciones",
                to="medicos.tipocancer",
            ),
        ),
    ]
