# Generated by Django 6.0 on 2025-12-15 17:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Especialidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ReunionComite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("fecha_programada", models.DateTimeField()),
                (
                    "duracion_estimada",
                    models.PositiveIntegerField(
                        default=60, help_text="Duración en minutos"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programada", "Programada"),
                            ("en_curso", "En Curso"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="programada",
                        max_length=20,
                    ),
                ),
                ("conclusiones", models.TextField(blank=True)),
                ("recomendaciones", models.TextField(blank=True)),
                ("fecha_inicio", models.DateTimeField(blank=True, null=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "acta_reunion",
                    models.FileField(
                        blank=True, null=True, upload_to="actas/comite/%Y/%m/"
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_programada"],
            },
        ),
        migrations.CreateModel(
            name="RevisionCaso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "tipo_revision",
                    models.CharField(
                        choices=[
                            ("individual", "Revisión Individual"),
                            ("comite", "Revisión en Comité"),
                        ],
                        default="individual",
                        max_length=20,
                    ),
                ),
                ("diagnostico_propuesto", models.TextField()),
                ("tratamiento_recomendado", models.TextField()),
                ("observaciones", models.TextField(blank=True)),
                ("conclusiones", models.TextField(blank=True)),
                ("coincidencia_diagnostico", models.BooleanField(default=False)),
                ("cambio_tratamiento", models.BooleanField(default=False)),
                ("requiere_discusion", models.BooleanField(default=False)),
                ("completada", models.BooleanField(default=False)),
                ("fecha_completada", models.DateTimeField(blank=True, null=True)),
                (
                    "informe_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="informes/revisiones/%Y/%m/"
                    ),
                ),
            ],
            options={
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="Medico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("cc", "Cédula de Ciudadanía"),
                            ("ce", "Cédula de Extranjería"),
                            ("ti", "Tarjeta de Identidad"),
                            ("pasaporte", "Pasaporte"),
                        ],
                        default="cc",
                        max_length=20,
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Solo números permitidos", regex="^\\d+$"
                            )
                        ],
                    ),
                ),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField()),
                (
                    "genero",
                    models.CharField(
                        choices=[
                            ("masculino", "Masculino"),
                            ("femenino", "Femenino"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "registro_medico",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Registro Médico"
                    ),
                ),
                ("experiencia_anios", models.PositiveIntegerField(default=0)),
                ("institucion_actual", models.CharField(max_length=100)),
                (
                    "telefono",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Formato de teléfono inválido",
                                regex="^\\+?[\\d\\s\\-\\(\\)]+$",
                            )
                        ],
                    ),
                ),
                (
                    "telefono_alternativo",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Formato de teléfono inválido",
                                regex="^\\+?[\\d\\s\\-\\(\\)]+$",
                            )
                        ],
                    ),
                ),
                ("email_institucional", models.EmailField(blank=True, max_length=254)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("suspendido", "Suspendido"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("disponible_segundas_opiniones", models.BooleanField(default=True)),
                ("max_casos_mes", models.PositiveIntegerField(default=10)),
                ("casos_actuales", models.PositiveIntegerField(default=0)),
                ("casos_revisados", models.PositiveIntegerField(default=0)),
                ("casos_comite", models.PositiveIntegerField(default=0)),
                (
                    "calificacion_promedio",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("fecha_ingreso", models.DateTimeField(auto_now_add=True)),
                ("ultimo_acceso", models.DateTimeField(blank=True, null=True)),
                (
                    "especialidades",
                    models.ManyToManyField(
                        related_name="medicos", to="medicos.especialidad"
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medico",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["apellidos", "nombres"],
            },
        ),
        migrations.CreateModel(
            name="DisponibilidadMedico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "dia_semana",
                    models.IntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ]
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("activo", models.BooleanField(default=True)),
                (
                    "medico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disponibilidad",
                        to="medicos.medico",
                    ),
                ),
            ],
            options={
                "ordering": ["dia_semana", "hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="ComiteMultidisciplinario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField()),
                ("min_medicos", models.PositiveIntegerField(default=3)),
                ("max_casos_simultaneos", models.PositiveIntegerField(default=5)),
                ("casos_actuales", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "especialidades_requeridas",
                    models.ManyToManyField(
                        related_name="comites", to="medicos.especialidad"
                    ),
                ),
                (
                    "medicos_miembros",
                    models.ManyToManyField(
                        blank=True, related_name="comites", to="medicos.medico"
                    ),
                ),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),
    ]
